#!/usr/bin/env python
def xkcdpwgen():  
    import argparse
    import random
    parser = argparse.ArgumentParser(
        description=
        'Generate a secure, memorable password using the XKCD method')
    parser.add_argument('-w',
                        '--words',
                        help='include WORDS words in the password (default=4)',
                        type=int,
                        default=4)
    parser.add_argument(
        '-c',
        '--caps',
        help='capitalize the first letter of CAPS random words (default=0)',
        type=int,
        default=0)
    parser.add_argument(
        '-n',
        '--numbers',
        help='insert NUMBERS random numbers in the password (default=0)',
        type=int,
        default=0)
    parser.add_argument(
        '-s',
        '--symbols',
        help='insert SYMBOLS random symbols in the password (default=0)',
        type=int,
        default=0)
    args = parser.parse_args()
    words = args.words
    caps = args.caps
    numbers = args.numbers
    symbols = args.symbols
    password = ""
    with open('words.txt', 'r') as f:
        word_list = f.read().splitlines()
    for i in range(words):
        password += random.choice(word_list).lower()
        if i < words - 1:
            password += " "
    for i in range(caps):
        #capitalize caps number of words in the password
        #select the words randomly from the password to capitalize
        word_to_cap = random.choice(password.split())
        #make sure the word isn't already capitalized
        while word_to_cap[0].isupper():
            word_to_cap = random.choice(password.split())
        #capitalize the first letter of the word
        word_to_cap = word_to_cap[0].upper() + word_to_cap[1:]
        #replace the word in the password with the capitalized word
        password = password.replace(word_to_cap.lower(), word_to_cap)
    for i in range(numbers):
        #insert numbers
        password += str(random.randint(0, 9))
    for i in range(symbols):
        #insert symbols
        password += random.choice(
            '!@#$%^&*()_-+={}[]|\:;"\'<>,.?/~`')
    #remove spaces from the password
    password = password.replace(" ", "")
    print(password)
    return
if __name__ == '__xkcdpwgen__':
    xkcdpwgen()
else:
  xkcdpwgen()
